### ISSUE TITLE
Unable to npm start myapplication with node_modules/fibers/future.js:280 ERROR

### ISSUE THREAD

**Issue by ghost** [VulcanJS/vulcanjs-cli#18]
Unable to npm start the app that i created by the tool and getting the following error.

`
=> Started proxy.                             
=> Started MongoDB.                           
W20180512-17:15:09.331(8)? (STDERR) /Users/kan/.meteor/packages/meteor-tool/.1.6.1_1.o8hqcq.5zvm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180512-17:15:09.542(8)? (STDERR) 						throw(ex);
W20180512-17:15:09.542(8)? (STDERR) 						^
W20180512-17:15:09.543(8)? (STDERR) 
W20180512-17:15:09.543(8)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20180512-17:15:09.543(8)? (STDERR)     at intl.js (packages/vulcan:lib/lib/server/intl.js:13:29)
W20180512-17:15:09.543(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180512-17:15:09.544(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180512-17:15:09.544(8)? (STDERR)     at main.js (packages/vulcan:lib/lib/server/main.js:1:824)
W20180512-17:15:09.544(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180512-17:15:09.545(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180512-17:15:09.545(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/packages/vulcan_lib.js:5334:15
W20180512-17:15:09.545(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/packages/vulcan_lib.js:5341:3
W20180512-17:15:09.545(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:411:36
W20180512-17:15:09.546(8)? (STDERR)     at Array.forEach (<anonymous>)
W20180512-17:15:09.546(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:220:19
W20180512-17:15:09.546(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:471:5
W20180512-17:15:09.546(8)? (STDERR)     at Function.run (/Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/profile.js:510:12)
W20180512-17:15:09.547(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
W20180512-17:15:21.234(8)? (STDERR) /Users/kan/.meteor/packages/meteor-tool/.1.6.1_1.o8hqcq.5zvm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180512-17:15:21.235(8)? (STDERR) 						throw(ex);
W20180512-17:15:21.235(8)? (STDERR) 						^
W20180512-17:15:21.236(8)? (STDERR) 
W20180512-17:15:21.236(8)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20180512-17:15:21.236(8)? (STDERR)     at intl.js (packages/vulcan:lib/lib/server/intl.js:13:29)
W20180512-17:15:21.236(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180512-17:15:21.237(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180512-17:15:21.237(8)? (STDERR)     at main.js (packages/vulcan:lib/lib/server/main.js:1:824)
W20180512-17:15:21.237(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180512-17:15:21.237(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180512-17:15:21.237(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/packages/vulcan_lib.js:5334:15
W20180512-17:15:21.238(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/packages/vulcan_lib.js:5341:3
W20180512-17:15:21.238(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:411:36
W20180512-17:15:21.238(8)? (STDERR)     at Array.forEach (<anonymous>)
W20180512-17:15:21.239(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:220:19
W20180512-17:15:21.239(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:471:5
W20180512-17:15:21.239(8)? (STDERR)     at Function.run (/Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/profile.js:510:12)
W20180512-17:15:21.239(8)? (STDERR)     at /Users/kan/Documents/kan/myapplication/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1

`

Module that i have imported is 
`
accounts-password  1.5.0* Password support for accounts
myapplication           0.0.0+
vulcan:core        1.10.0+ Vulcan core package
vulcan:debug       1.10.0+ Vulcan debug package
vulcan:i18n-en-us  1.10.0+ Vulcan i18n package (en_US)
`

And i'm running the following version

`
> meteor --version      
Meteor 1.6.1.1
> npm --v
5.6.0
> node --version
v8.11.1
`

Anyone could shed some light please?

**Comment by ghost** [comment]
i guess it maybe the problem of meteor and so i raised an issue over the meteor forum

https://forums.meteor.com/t/unable-to-npm-start-myapplication-with-node-modules-fibers-future-js-280-error/43645

**Comment by SachaG** [comment]
I'm not sure but note that the CLI project is not currently maintained. But we're looking for maintainers, if you're interested :)

**Comment by ghost** [comment]
it will be great if that works, as you mentioned it a very good tool to help new starter to understand and use vulcan

**Comment by mechanical-turk** [comment]
@kankando @SachaG hey everyone. I used to maintain this project back when I used to work on open source projects full time. my current occupation doesn't let me maintain this project anymore. since I stopped, vulcan has advanced significantly. I'll go ahead and write a little description on the readme so that users dont get confused. thanks for your time @kankando
