### ISSUE TITLE
route generation overwrite message is misleading

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/vulcanjs-cli#25]
When you generate a new route, when you select overwrite, it actually appends instead of overwrites.

**Comment by eric-burel** [comment]
Yeah sorry, but this is the behaviour of Yeoman. Appending to routes is actually an overwrite of the file, and we can't disable the overwrite message (https://stackoverflow.com/questions/37006786/force-overwrite-file). Maybe there is a better approach but I did not find it.
