### ISSUE TITLE
Generating packages does not work on projects not initiated with vulcanjs-cli

### ISSUE THREAD

**Issue by ayhid** [VulcanJS/vulcanjs-cli#3]
I have a vulcan project cloned manually using git, when trying to generate a package using `vulcanjs g package <project-name>`
I get this error `This is not a Vulcan.js project directory.`

**Comment by mechanical-turk** [comment]
@ayhid thanks for the report. This shows that we do need an --init function, just like @albancrommer suggested. I'll take a look soon.

**Comment by mechanical-turk** [comment]
`vulcan init` will now let update a non-cli vulcan project to a vulcan-cli-friendly one
